version: "3.9"

services:

  postgres:

    restart: no
    image: "postgres:16.3"
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgers
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres-data-vol:/var/lib/postgresql/data
      - flyway-migration-vol:/flyway/sql/
    networks:
      - postgres-net

  test-gm:

    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    container_name: test-gm
    working_dir: /TestGM
    command: bash -c "
      /opt/poetry-venv/bin/poetry run alembic upgrade head
      && /opt/poetry-venv/bin/poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*' --proxy-headers
      "
    ports:
     - "8000:8000"
    networks:
     - postgres-net

volumes:
  postgres-data-vol:
  flyway-migration-vol:

networks:
  postgres-net:
