from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0afaebc7111d'
down_revision: Union[str, None] = '2dbab63d222c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'notification_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Interval(),
               existing_nullable=False,
               postgresql_using="(notification_time - current_timestamp)::interval")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'notification_time',
               existing_type=sa.Interval(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               postgresql_using="(current_timestamp + notification_time)::timestamp")
    # ### end Alembic commands ###
