"""update notification table

Revision ID: 2dbab63d222c
Revises: bc07e99c7bbe
Create Date: 2024-06-07 12:03:44.088847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dbab63d222c'
down_revision: Union[str, None] = 'bc07e99c7bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('subscription_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'notification', ['subscription_id'])
    op.drop_constraint('notification_user_id_fkey', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'subscribe', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.drop_column('notification', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key('notification_user_id_fkey', 'notification', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'notification', type_='unique')
    op.drop_column('notification', 'subscription_id')
    # ### end Alembic commands ###
