"""remove field notificated from table

Revision ID: 433babd18a9f
Revises: fdc1dccae575
Create Date: 2024-06-07 22:01:38.757045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433babd18a9f'
down_revision: Union[str, None] = 'fdc1dccae575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'notificated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('notificated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
