"""add tokens blacklist

Revision ID: 49ad3e776188
Revises: 4d2cef32569e
Create Date: 2024-06-06 10:13:19.779250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ad3e776188'
down_revision: Union[str, None] = '4d2cef32569e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist_outstanding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('exp', sa.Integer(), nullable=False),
    sa.Column('iat', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_blacklisted',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('token_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['token_blacklist_outstanding.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklisted')
    op.drop_table('token_blacklist_outstanding')
    # ### end Alembic commands ###
