"""update notification_time field in notification table

Revision ID: 72009059ec6e
Revises: 45d4eb5be09f
Create Date: 2024-06-07 16:27:17.235608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72009059ec6e'
down_revision: Union[str, None] = '45d4eb5be09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE notification 
            ALTER COLUMN notification_time TYPE TIMESTAMP WITHOUT TIME ZONE 
            USING (NOW() + notification_time)
        """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'notification_time',
               existing_type=sa.DateTime(),
               type_=postgresql.INTERVAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
