"""set unique_constraint to follower and followed

Revision ID: fdc1dccae575
Revises: 72009059ec6e
Create Date: 2024-06-07 19:45:40.698387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc1dccae575'
down_revision: Union[str, None] = '72009059ec6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_follower_followed', 'subscribe', ['follower_id', 'followed_id'])
    op.alter_column('user', 'birthday',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'birthday',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint('unique_follower_followed', 'subscribe', type_='unique')
    # ### end Alembic commands ###
